### ISSUE TITLE
Stackpath CDN is unavailable in Egypt

### ISSUE THREAD

**Issue by mahmoud-bahaa** [livepeer/go-livepeer#2750]
**Describe the bug**
The Stackpath CDN is not reachable in Egypt and potentially other countries. This problem prevents the client from playing any Livepeer videos.

**To Reproduce**
1. Try to stream from Egypt. 
2. Playback fails with ERR_BLOCKED_BY_CLIENT

**Expected behavior**
Playback should work as usual. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**
 - Version 110.0.5481.77

**Additional context**
I already discussed this with the Livepeer team over Zoom. This is a placeholder to track the progress.

**Comment by thomshutt** [comment]
We believe this is now resolved, but please feel free to reopen if there's a recurrence

**Comment by Shih-Yu** [comment]
Just got confirmation that it still not working and only displaying a continuous buffer.
