### ISSUE TITLE
run CLI web server in Transcoder-only mode

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#747]
**Is your feature request related to a problem? Please describe.**
Right now transcoder-only node doesn't run any http server (nor CLI, nor media), so there is no way to externally check if node is still alive. For B/O I'm setting up 'Uptime' check - which periodically probes `/status` endpoint and sends alert email if it's not responding for too long. I can't do same for transcoder-only node. 

**Describe the solution you'd like**
Start CLI webserver with one endpoint `/status`.

**Describe alternatives you've considered**
Do nothing for now.

**Comment by j0sh** [comment]
Another option is to expose transcoder connectivity information via the orchestrator itself. It'd be nice to keep the "surface area" of the transcoder node itself as small as possible, so it doesn't have to be exposed just for status checks, which isn't a fundamental feature.

The O's `/status` (or some other endpoint, eg `/transcoders`) could return a list of currently connected transcoders. If the list does not match what's expected then we could send out an alert.

Long term we probably should add ping/pong keepalives so we'd know when the last communication with the transcoder was, making this a more reliable status indicator. If the O transmits this, it could serve as a latency indicator during idle periods. IIRC the reason we don't have "O-initiated keepalives" right now is because we can't really do bidirectional RPC; we can't have logical/virtual client/servers atop an underlying physical connection that was initiated by the opposite party. There seem to be [workarounds](https://github.com/grpc/grpc-go/issues/484) to this, which we can evaluate later.

**Comment by darkdarkdragon** [comment]
@j0sh 
> Another option is to expose transcoder connectivity information via the orchestrator itself.

This really wouldn't be enough. Transcoders potentially will be running far away from orchestrator, and we need to be able to monitor transcoder process itself, not just check if it is still connected to orchestrator.

**Comment by angyangie** [comment]
Interesting discussion! What do you mean by `monitor transcoder process itself` @darkdarkdragon ?

**Comment by darkdarkdragon** [comment]
@angyangie 
Standalone transcoder - it is separate process in the operating system, probably running on separate physical machine and contacting orchestrator through network. I want to get metrics from that process itself, and not guess if it is still running/how well it is doing by checking if it is still connected to orchestrator or not.

**Comment by angyangie** [comment]
Thanks for the explanation @darkdarkdragon!

**Comment by ericxtang** [comment]
Is this addressed by the new metrics system?  Transcoder can now report metrics through OpenCensus. cc @darkdarkdragon

**Comment by darkdarkdragon** [comment]
@ericxtang 
No, this issue wasn't addressed - we still not running web server for transcode-only nodes.

**Comment by yondonfu** [comment]
Closed by #1650
